In [2]:
import numpy as np

In [3]:
#checking the version of numpy if it is installed it will show the np version
print(np.__version__)

2.4.4


In [ ]:
# starting with simple example 

In [4]:
#without numpy
numbers = [1,2,3,4]

new=[]
for i in numbers:
    new.append(i*2)
print("Without using number ")
print(new)

[2, 4, 6, 8]


In [6]:
#with numpy
numbers=np.array([1,2,3,4])
print("With using number ")

print(numbers*2)

With using number 
[2 4 6 8]


# QUESTION 1: 
CREATING MY FIRST ARRAY 

In [7]:
firstarray=np.array([10,20,30,40])
print("My first Array is: ",firstarray)

My first Array is:  [10 20 30 40]


In [8]:
# string array
strArr=np.array(["Apple","Banana","Orange"])
print("String array is :",strArr)

String array is : ['Apple' 'Banana' 'Orange']


# MULTIDIMENTIONAL ARRAYS

In [9]:
# 1-Dimentional Array 
one=np.array([1,2,3,4,5])
print(one)

[1 2 3 4 5]


In [13]:
# 2-Dimensional Array
twoD=np.array([
    [2,4,6,8],[1,3,5,7]
])
print("Two D array is :\n",twoD)

Two D array is :
 [[2 4 6 8]
 [1 3 5 7]]


In [15]:
# THREE-DIMENSIONAL ARRAY
three_D=([
   [
       [1,2],
       [3,4]
   ],
   [
        [5,6],
        [7,8]
    ]
    
])
print("3-D ARRAY ARE:",three_D)

3-D ARRAY ARE: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [27]:
# Mini CHALLENGE
MINI=np.array([
    [[2,3],[4,5]],
    [[19,20],[21,22]]
                        ])
print("Mini Task")
print(MINI)

Mini Task
[[[ 2  3]
  [ 4  5]]

 [[19 20]
  [21 22]]]


# KEYWORDS TO CHECK DATA STRUCTURE

In [33]:
# TO CHECK DIMENSION OF THE MATRIX USE ndim
print("DIMENSION IS:",MINI.ndim)

# TO CHECK SHAPE USE shape
print("SHAPE IS:",MINI.shape)

# TO CHECK SIZE OF THE MATRIX use size
print("SIZE IS:",MINI.size)

# TO CHECK DATA TYPE USE dtype
print("DATA TYPE IS:",MINI.dtype)

# TO CHECK BYTES USE nbytes
print("Bytes are:",MINI.nbytes)

# TO CHECK ITEM SIZE USE itemsize
print("Item Size is:",MINI.itemsize)

DIMENSION IS: 3
SHAPE IS: (2, 2, 2)
SIZE IS: 8
DATA TYPE IS: int64
Bytes are: 64
Item Size is: 8


# -------------------------------------------------------------------------------------------------------------------------

# CREATING ARRAYS 

## ZEROS()

In [29]:
#             using keyword(zeros)
#create an array filled with zeros 

firstz=np.zeros(5) # float by default and 1 row 5 zeros 
print(firstz)

[0. 0. 0. 0. 0.]


In [31]:
#  TWO ROWS Two COLUMNS
twoz=np.zeros((2,2))
print(twoz)

[[0. 0.]
 [0. 0.]]


## ONES()

In [35]:
firstO=np.ones(5)
print(firstO)

[1. 1. 1. 1. 1.]


In [36]:
# THREE ROWS FOUR COLUMNS OF 1 
multiOne=np.ones((3,4))
print(multiOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## full() to fill any kind of number specifically

In [37]:
fillAny=np.full((2,2),3) #2and2 is row and columns 3 is number which gonna be filled in
print(fillAny)

[[3 3]
 [3 3]]


# IDENTITY MATRIX->
USING eye()

In [39]:
ident=np.eye(5) # size 5 of identity matrix
print(ident)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# arange()
its like a python range but arange() return us a numpy array 

In [40]:
aran=np.arange(14)
print(aran)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


# start and stop in arange()

In [41]:
a=np.arange(5,15) #starting from 5 ends at 14
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


# start stop and step 

In [42]:
b=np.arange(0,12,2) # start from 0 ends at 11 gap of 2
print(b)

[ 0  2  4  6  8 10]


# linspace()
Very common in plotting and machine learning.
Instead of step size, you specify how many numbers you want.
Meaning:

Give me 5 equally spaced numbers between 0 and 10 (including both ends).

In [45]:
lp=np.linspace(0,50,6) # divide numbers in 5 segments
print(lp)

[ 0. 10. 20. 30. 40. 50.]


# GENERATE RANDOM ARRAYS USING random()

In [51]:
ran=np.random.rand(6) # rand() will give decimal values
print(ran)

[0.84158981 0.71163946 0.3182494  0.69914784 0.58776479 0.11719311]


In [49]:
# random integers
ranInt=np.random.randint(1,11,5) # 1 se 11 space and divide into 5
print(ranInt)

[10  4  4  4  2]


In [57]:
# mini matrix challenge 
minchall=np.arange(10,100,10).reshape(3,3)
print(minchall)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


# LESSON 4: ARRAY OPERATIONS (VECTORIZATION)

In [58]:
# create an Array 
A=np.array([10,20,30,40,50])
print(A)

[10 20 30 40 50]


In [61]:
#Original Array
print("Originl Array: ",A)
#Addition
print("\n\nAddition is:",A+5)
#subtraction
print("Subtraction is:",A-5)
#Multiplication
print("Multiplication is:",A*5)
#Division
print("Division is:",A/5)


Originl Array:  [10 20 30 40 50]


Addition is: [15 25 35 45 55]
Subtraction is: [ 5 15 25 35 45]
Multiplication is: [ 50 100 150 200 250]
Division is: [ 2.  4.  6.  8. 10.]


# ARRAY + ARRAY 
Both Matrix should be of same size 

In [65]:
A=np.array([10,20,30])
B=np.array([2,2,2])
print("Addition of two arrays are: ",A+B)


#SAME METHOD CAN BE PERFOR FOR OTHER PERATIONS 


Addition of two arrays are:  [12 22 32]


In [70]:
#2D ARRAYS (element wise = element to element operation)
C=np.array([[1,2],[3,4]])
D=np.array([[5,6],[7,8]])
print("2D array \n",C+D)

2D array 
 [[ 6  8]
 [10 12]]


# MATRIX MULTIPLCATION 
* ->.dot(A+b) (element wise )example
@-> matrix to matrix calculation


1. * — Element-wise Multiplication (Hadamard Product)The * operator multiplies corresponding elements in the exact same positions.
    How it works:If you have two matrices $A$ and $B$:$$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$$Applying A * B multiplies $A[i, j]$ by $B[i, j]$:$$A * B = \begin{bmatrix} 1 \times 5 & 2 \times 6 \\ 3 \times 7 & 4 \times 8 \end{bmatrix} = \begin{bmatrix} 5 & 12 \\ 21 & 32 \end{bmatrix}




2. @ — Matrix Multiplication (Dot Product)

3. The @ operator performs standard Linear Algebra matrix multiplication (taking the dot product of rows from $A$ and columns from $B$).How it works:Using the same matrices $A$ and $B$:Top-Left: Row 1 of $A$ $\cdot$ Column 1 of $B$ $\rightarrow (1 \times 5) + (2 \times 7) = 5 + 14 = \mathbf{19}$Top-Right: Row 1 of $A$ $\cdot$ Column 2 of $B$ $\rightarrow (1 \times 6) + (2 \times 8) = 6 + 16 = \mathbf{22}$Bottom-Left: Row 2 of $A$ $\cdot$ Column 1 of $B$ $\rightarrow (3 \times 5) + (4 \times 7) = 15 + 28 = \mathbf{43}$Bottom-Right: Row 2 of $A$ $\cdot$ Column 2 of $B$ $\rightarrow (3 \times 6) + (4 \times 8) = 18 + 32 = \mathbf{50}$$$A \text{ @ } B = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}$$

In [74]:
# ELEMENT WISE *
print(C*D)
#ornp.multiply(C,D)

[[ 5 12]
 [21 32]]


In [75]:
# MATRIX MULTIPLICATION @
print(C@D)

# * OR .DOT EXAMPLE IS 
#print(np.dot(C,D))

[[19 22]
 [43 50]]


# USEFULL MATHEMATICAL FUNCTIONS 
 squarRoot,Square,AbsoluteValue,ExponentialValue,Logarithm,Sine
,Cosine

In [77]:
#Create an array to work on 
A=np.array([4,9,16,25,30])
print("Array with square root is: \n",np.sqrt(A))


Array with square root is: 
 [2.         3.         4.         5.         5.47722558]


In [78]:
# square
print("Squaring on Array: \n",np.square(A))

Squaring on Array: 
 [ 16  81 256 625 900]


In [82]:
# Absolute Value
# for that we need negative values in the array 
#creating new array
A=np.array([2,-3,-4,-10,-20,22,24])
print("Absolute Value of Array:\n",np.abs(A))

Absolute Value of Array:
 [ 2  3  4 10 20 22 24]


In [83]:
#Exponential Values
print(np.exp([1,2,3]))

[ 2.71828183  7.3890561  20.08553692]


In [84]:
#Logarithmic 
print(np.log([1,2,3]))

[0.         0.69314718 1.09861229]


In [86]:
#Sine
print(np.sin(np.pi/2))

1.0


In [87]:
#Cosine
print(np.cos(0))

1.0


# Comparison Operations
>
==
<
!=

In [89]:
# create array 
A=np.array([10,20,30,40,50])
print(A>25)#greater than
print(A == 30)#equal to
print(A!=20)#not equal to

[False False  True  True  True]
[False False  True False False]
[ True False  True  True  True]
